### ISSUE TITLE
vine: `break` with value

### ISSUE THREAD

**Issue by tjjfvi** [VineLang/vine#66]
In `loop`s, `break` could be supplied a value, which would become the result of the `loop` expression.

The most complicated part of this would likely be the parsing, as there's not currently a mechanism to optionally parse an expression. (Though this would be useful for `return` as well.)

**Comment by stevenhuyn** [comment]
Should we invent a `()` type then to add to `ExprKind`?

**Comment by tjjfvi** [comment]
`ExprKind::Tuple(vec![])` works for that
