### ISSUE TITLE
vine: infinite loop miscompilation

### ISSUE THREAD

**Issue by tjjfvi** [VineLang/vine#70]
```rs
use std::io::print_char;

fn main(io) {
  loop {
    io.print_char('*');
  }
}
```

This prints a single asterisk and then exits. Correct behavior would be either printing `*`s indefinitely, or printing finitely many `*`s and then hanging. (This is just up to reduction order.)

**Comment by stevenhuyn** [comment]
is the either because you're not sure or because it's not deterministic?

**Comment by tjjfvi** [comment]
It is non-deterministic in the sense that a valid Ivy interpreter could choose to do either one of them. For a specific Ivy interpreter, it would likely always be one of the two options (though it could be random). I believe for the current implementation of Ivy, it would print `*`s indefinitely.

**Comment by tjjfvi** [comment]
[A random evaluation order would [almost always](https://en.wikipedia.org/wiki/Almost_surely) print `*`s indefinitely.]

**Comment by stevenhuyn** [comment]
> It is non-deterministic in the sense that a valid Ivy interpreter could choose to do either one of them. 

kk so the spec doesn't define the evaluation order, but an actual implementation probably would. Thus in practice it's deterministic.
